config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"

  mount Sidekiq::Web => "/sidekiq"

  root "client/dashboard#index"

  scope module: "client", path: "", as: "" do
    devise_for :accounts, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :records, only: [:new, :create, :show] do 
      member do
        get :hira_kata
        get :radical
        get :hira_kata_export_pdf
        get :radical_export_pdf
        get :kanji_export_pdf
      end
    end
    resources :accounts, only: [:show] do
      member do
        get :billing_history
      end
    end

    get "/search", to: "dashboard#search_kanji", as: :search_kanji
    get "/translate", to: "dashboard#translate", as: :translate
    get "/podcast", to: "dashboard#podcast", as: :podcast
    get "/checkout", to: "dashboard#checkout", as: :checkout
    get "/contact", to: "dashboard#contact", as: :contact
  end

  namespace :admin do
    root "dashboard#index"
   
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :accounts
    resources :histories, only: [:index, :show]
    resources :kanjis
    resources :story_kanjis
  end
end

app/controllers/client/accounts_controller.rb
# frozen_string_literal: true

class Client::AccountsController < Client::BaseController
  before_action :set_account, only: [:show, :billing_history]

  def show
  end

  def billing_history
  end

  private

  def set_account
    @account = Account.friendly.find(params[:id])
  end
end

app/controllers/client/base_controller.rb
# frozen_string_literal: true

class Client::BaseController < ApplicationController
  # before_action :authenticate_account!
end

app/controllers/client/dashboard_controller.rb
# frozen_string_literal: true

class Client::DashboardController < Client::BaseController
  def index
    @record = Record.new
  end

  def search_kanji
    @q = Kanji.ransack(params[:q])
    @pagy, @kanjis = pagy(@q.result.order(created_at: :desc))

    @kanji = (@kanjis.last if @kanjis.count == 1)
  end

  def translate
  end

  def podcast
  end

  def checkout
  end

  def contact
  end
end

app/controllers/client/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Client::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    generic_callback(:google_oauth2)
  end

  def generic_callback provider
    @account = Account.from_omniauth(request.env["omniauth.auth"])
    account_exits = Account.where("email = ? and provider != ?", @account.email, provider).take
    return handle_account_exits(account_exits, provider) if account_exits

    if @account.persisted?
      set_flash_message(:notice, :success, kind: provider.capitalize)
    else
      @account.email = @account.uid if @account.email.blank?
      @account.save(validate: false)
      @account.histories.create(
        type_history: "create_account",
        title: "Chào mừng bạn đến với hệ thống!",
        description: "Chúc bạn có những trải nghiệm thú vị trong hành trình học tiếng Nhật."
      )
      ActionAccountMailer.send_email_welcome(@account.email, @account.full_name).deliver_later
    end
    @account.update last_sign_in_at: Time.zone.now
    sign_in_and_redirect @account, event: :authentication
  end

  def failure
    redirect_to root_path
  end

  private

  def handle_account_exits account_exits, provider
    account_exits.uid = @account.uid
    account_exits.provider = provider

    account_exits.save
    set_flash_message(:notice, :success, kind: provider.capitalize)
    sign_in_and_redirect account_exits, event: :authentication
  end
end

app/controllers/client/records_controller.rb
# frozen_string_literal: true

class Client::RecordsController < Client::BaseController
  before_action :render_service,
    only: [:show, :hira_kata, :radical, :hira_kata_export_pdf, :radical_export_pdf, :kanji_export_pdf]
  before_action :set_record, only: :show

  def show # rubocop:disable Metrics/PerceivedComplexity
    if @record.hiragana? || @record.katakana?
      if @record.kanji_list.include?("じ") || @record.kanji_list.include?("ジ")
        redirect_to hira_kata_record_path(@record)
      else
        flash[:error] = "Tạo bản nháp Hiragana hoặc Katakana nhưng nội dung không khớp, vui lòng chọn lại"
        redirect_to root_path
      end
    end

    return unless @record.sub_kanji?

    if @record.kanji_list.include?("衣")
      redirect_to radical_record_path(@record)
    else
      flash[:error] = "Tạo bản nháp 214 bộ thủ nhưng nội dung không khớp, vui lòng chọn lại"
      redirect_to root_path
    end
  end

  def create # rubocop:disable Metrics/MethodLength,Metrics/PerceivedComplexity
    unless account_signed_in?
      flash[:error] = "Bạn cần đăng nhập để sử dụng tính năng này"
      redirect_to root_path
      return
    end

    if current_account.advanced?
      @record = Record.new record_params
      @record.account_id = current_account.id
      @record.name = "Code=#{SecureRandom.uuid}-#{Time.zone.now.to_i}"

      if @record.save
        flash[:success] = "Tạo bản ghi thành công."
        current_account.histories.create(
          type_history: "download",
          title: "Tạo bản nháp thành công.",
          description: "Chúc bạn học thật tốt với file luyện viết này",
          record_id: @record.id
        )
        redirect_to @record
      else
        flash[:error] = "Tạo bản ghi thất bại."
        redirect_to root_path
      end
    elsif record_params[:type_record] == "hiragana" ||
          record_params[:type_record] == "katakana" || record_params[:type_record] == "sub_kanji"
      @record = Record.new record_params
      @record.account_id = current_account.id
      @record.name = "Code=#{SecureRandom.uuid}-#{Time.zone.now.to_i}"
      @record.title = "luyenkanji.com | @thocodehoctiengnhat"

      if @record.save
        flash[:success] = "Tạo bản ghi thành công."
        current_account.histories.create(
          type_history: "download",
          title: "Tạo bản nháp thành công.",
          description: "Chúc bạn học thật tốt với file luyện viết này",
          record_id: @record.id
        )
        redirect_to @record
      else
        flash[:error] = "Tạo bản ghi thất bại."
        redirect_to root_path
      end
    else
      flash[:error] = "Bạn cần nâng cấp tài khoản để sử dụng tùy chọn này."
      redirect_to root_path
    end
  end

  def hira_kata
  end

  def radical
  end

  def hira_kata_export_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
          template: "client/records/hira_kata_export_pdf",
          formats: [:html],
          disposition: :attachment,
          layout: "pdf"
      end
    end
  end

  def radical_export_pdf
    render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
      disposition: "attachment",
      layout: "pdf"
  end

  def kanji_export_pdf
    render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
      disposition: "attachment",
      layout: "pdf"
  end

  private

  def record_params
    params.require(:record).permit Record::ATTRS
  end

  def set_record
    @record = Record.friendly.find(params[:id])
  end

  def render_service
    @record = Record.friendly.find(params[:id])
    svg = HandleSvgService.new
    @list_path = svg.handle_kanji @record.kanji_list
  end
end

app/controllers/client/sessions_controller.rb
# frozen_string_literal: true

class Client::SessionsController < Devise::SessionsController
  layout "client/unauthenticate_layout"

  def destroy
    flash[:success] = I18n.t("devise.sessions.signed_out") if sign_out current_account
    redirect_to new_account_session_path
  end
end

app/views/layouts/client/_header.html.erb
<div
  id="kt_app_header"
  class="app-header"
  data-kt-sticky="true"
  data-kt-sticky-activate-="true"
  data-kt-sticky-name="app-header-sticky"
  data-kt-sticky-offset="{default: '200px', lg: '300px'}">
  <div class="app-container container-xxl d-flex align-items-stretch justify-content-between"
    id="kt_app_header_container">
    <div class="app-header-wrapper d-flex flex-grow-1 align-items-stretch justify-content-between"
      id="kt_app_header_wrapper">
      <div class="d-flex align-items-center">
        <div class="btn btn-icon btn-color-gray-600 btn-active-color-primary ms-n3 me-2 d-flex d-lg-none"
          id="kt_app_sidebar_toggle">
          <i class="ki-outline ki-abstract-14 fs-2"></i>
        </div>
        <a href="/" class="d-flex d-lg-none">
          <img
            alt="Logo"
            src="<%= asset_path("media/logos/kanji.svg") %>"
            class="h-20px theme-light-show"
          />
          <img
            alt="Logo"
            src="<%= asset_path("media/logos/kanji-dark.svg") %>"
            class="h-20px theme-dark-show"
          />
        </a>
      </div>
      <div class="app-navbar flex-shrink-0">
        <div class="app-navbar-item ms-1 ms-lg-3">
          <div class="btn btn-icon btn-circle btn-color-gray-500 btn-active-color-primary btn-custom shadow-xs bg-body" id="kt_drawer_chat_toggle">
            <i class="ki-outline ki-message-notif fs-1"></i>
          </div>
        </div>
        <div class="app-navbar-item ms-1 ms-lg-3">
          <div class="app-navbar-item btn btn-icon btn-circle btn-color-gray-500 btn-active-color-primary btn-custom shadow-xs bg-body">
            <a href="#"
              class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-35px h-35px"
              data-kt-menu-trigger="{default:'click', lg: 'hover'}"
              data-kt-menu-attach="parent"
              data-kt-menu-placement="bottom-end" >
              <i class="ki-duotone ki-night-day theme-light-show fs-1" >
                <span class="path1"></span><span class="path2"></span>
                <span class="path3"></span><span class="path4"></span>
                <span class="path5"></span><span class="path6"></span>
                <span class="path7"></span><span class="path8"></span>
                <span class="path9"></span><span class="path10"></span>
              </i>
              <i class="ki-duotone ki-moon theme-dark-show fs-1">
                <span class="path1"></span>
                <span class="path2"></span>
              </i>
            </a>
            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-title-gray-700 menu-icon-gray-500 menu-active-bg menu-state-color fw-semibold py-4 fs-base w-150px"
              data-kt-menu="true"
              data-kt-element="theme-mode-menu">
              <div class="menu-item px-3 my-0">
                <a href="#"
                  class="menu-link px-3 py-2"
                  data-kt-element="mode"
                  data-kt-value="light">
                  <span class="menu-icon" data-kt-element="icon">
                    <i class="ki-duotone ki-night-day fs-2"
                      ><span class="path1"></span
                      ><span class="path2"></span
                      ><span class="path3"></span
                      ><span class="path4"></span
                      ><span class="path5"></span
                      ><span class="path6"></span
                      ><span class="path7"></span
                      ><span class="path8"></span
                      ><span class="path9"></span
                      ><span class="path10"></span
                    ></i>
                  </span>
                  <span class="menu-title"> Light </span>
                </a>
              </div>

              <div class="menu-item px-3 my-0">
                <a
                  href="#"
                  class="menu-link px-3 py-2 active"
                  data-kt-element="mode"
                  data-kt-value="dark"
                >
                  <span class="menu-icon" data-kt-element="icon">
                    <i class="ki-duotone ki-moon fs-2"
                      ><span class="path1"></span
                      ><span class="path2"></span
                    ></i>
                  </span>
                  <span class="menu-title"> Dark </span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/client/_sidebar.html.erb
<div
  id="kt_app_sidebar"
  class="app-sidebar flex-column"
  data-kt-drawer="true"
  data-kt-drawer-name="app-sidebar"
  data-kt-drawer-activate="{default: true, lg: false}"
  data-kt-drawer-overlay="true"
  data-kt-drawer-width="275px"
  data-kt-drawer-direction="start"
  data-kt-drawer-toggle="#kt_app_sidebar_toggle">
  <div
    class="d-flex flex-stack px-4 px-lg-6 py-3 py-lg-8"
    id="kt_app_sidebar_logo">
    <a href="/">
      <img alt="Logo" src="<%= asset_path("media/logos/kanji.svg")%>" class="h-20px h-lg-25px theme-light-show" />
      <img alt="Logo" src="<%= asset_path("media/logos/kanji-dark.svg")%>" class="h-20px h-lg-25px theme-dark-show"/>
    </a>
    <% if account_signed_in? %>
      <div class="ms-3">
        <div class="cursor-pointer position-relative symbol symbol-circle symbol-40px"
          data-kt-menu-trigger="{default: 'click', lg: 'hover'}"
          data-kt-menu-attach="parent"
          data-kt-menu-placement="bottom-end">
          <img src="<%= current_account.photo_url %>" alt="user" />
          <div class="position-absolute rounded-circle bg-success start-100 top-100 h-8px w-8px ms-n3 mt-n3"></div>
        </div>
        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-325px"
          data-kt-menu="true">
          <div class="menu-item px-3">
            <div class="menu-content d-flex align-items-center px-3">
              <div class="symbol symbol-50px me-5">
                <img alt="Logo" src="<%= current_account.photo_url %>" alt="user"/>
              </div>
              <div class="d-flex flex-column">
                <div class="fw-bold d-flex align-items-center fs-5">
                  <%= current_account.full_name %>
                  <span class="badge badge-light-success fw-bold fs-8 px-2 py-1 ms-2"><%= current_account.role %></span>
                </div>
                <a href="#" class="fw-semibold text-muted text-hover-primary fs-7"><%= current_account.email %></a>
              </div>
            </div>
          </div>
          <div class="separator my-2"></div>
          <div class="menu-item px-5">
            <a href="<%= account_path(current_account) %>" class="menu-link px-5">Hồ sơ cá nhân</a>
          </div>
          <div class="menu-item px-5">
            <a href="/"
              class="menu-link px-5">
              <span class="menu-text">Lịch sử tải file</span>
              <span class="menu-badge">
                <span class="badge badge-light-danger badge-circle fw-bold fs-7"><%= current_account.records.count %></span>
              </span>
            </a>
          </div>
        </div>
      </div>
    <% else %>
      <div class="ms-3">
        <div class="cursor-pointer symbol symbol-circle symbol-40px">
          <%= link_to new_account_session_path, class: "btn btn-sm btn-icon btn-active-color-primary btn-icon-gray-600 btn-text-gray-600 w-auto" do %>
            <i class="ki-duotone ki-entrance-right fs-1 me-2"><span class="path1"></span><span class="path2"></span></i>
            <span class="d-flex flex-shrink-0 fw-bold">Đăng Nhập</span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex-column-fluid px-4 px-lg-8 py-4" id="kt_app_sidebar_nav">
    <div id="kt_app_sidebar_nav_wrapper"
        class="d-flex flex-column hover-scroll-y pe-4 me-n4"
        data-kt-scroll="true"
        data-kt-scroll-activate="true"
        data-kt-scroll-height="auto"
        data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer"
        data-kt-scroll-wrappers="#kt_app_sidebar, #kt_app_sidebar_nav"
        data-kt-scroll-offset="5px">
        <div class="mb-6">
          <h3 class="text-gray-800 fw-bold mb-8">Tiện ích</h3>
          <div
            class="row row-cols-3"
            data-kt-buttons="true"
            data-kt-buttons-target="[data-kt-button]"
          >
            <div class="col mb-4">
              <a
                href="<%= search_kanji_path %>"
                class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(search_kanji_path, "dashboard", "search_kanji") %>"
              >
                <span class="mb-2">
                  <i class="ki-outline ki-calendar fs-1"></i>
                </span>
                <span class="fs-7 fw-bold">Tìm Kanji</span>
              </a>
            </div>
            <div class="col mb-4">
              <a href="<%= translate_path %>"
                class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(translate_path, "dashboard", "translate") %>">
                <span class="mb-2">
                  <i class="ki-outline ki-security-check fs-1"></i>
                </span>
                <span class="fs-7 fw-bold">Dịch bằng AI</span>
              </a>
            </div>
            <div class="col mb-4">
              <a href="<%= podcast_path %>"
                class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px  <%= active_sidebar(podcast_path, "dashboard", "podcast") %>">
                <span class="mb-2">
                  <i class="ki-outline ki-wifi-square fs-1"></i>
                </span>
                <span class="fs-7 fw-bold">Nghe hiểu</span>
              </a>
            </div>
            <div class="col mb-4">
              <a
                href=""
                class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px border-gray-200"
              >
                <span class="mb-2">
                  <i class="ki-outline ki-chart-line-up-2 fs-1"></i>
                </span>
                <span class="fs-7 fw-bold">Đọc hiểu</span>
              </a>
            </div>
            <div class="col mb-4">
              <a href="https://www.facebook.com/groups/thocodehoctiengnhat" target="_blank" class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px border-gray-200" >
                <span class="mb-2">
                  <i class="ki-duotone ki-facebook fs-1">
                    <span class="path1"></span>
                    <span class="path2"></span>
                  </i>
                </span>
                <span class="fs-7 fw-bold">Thảo luận</span>
              </a>
            </div>
            <div class="col mb-4">
              <a href="<%= root_path %>" class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(root_path, "dashboard") %>">
                <span class="mb-2">
                  <i class="ki-outline ki-geolocation-home fs-1"></i>
                </span>
                <span class="fs-7 fw-bold">Trang chủ</span>
              </a>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="aside-footer flex-column-auto px-4 px-lg-8 py-3 py-lg-8" id="kt_app_sidebar_footer">
    <div class="d-flex flex-stack">
      <% if account_signed_in? %>
        <div class="ms-7">
            <%= link_to destroy_account_session_path, class: "btn btn-sm btn-icon btn-active-color-primary btn-icon-gray-600 btn-text-gray-600" do %>
              <i class="ki-duotone ki-entrance-left fs-1 me-2"><span class="path1"></span><span class="path2"></span></i>
              <span class="d-flex flex-shrink-0 fw-bold">Đăng xuất</span>
            <% end %>
        </div>
      <% end %>
      <div class="btn btn-sm btn-icon btn-icon-gray-600 btn-active-color-primary position-relative me-n1">
        <i class="ki-duotone ki-setting-2 fs-1"><span class="path1"></span><span class="path2"></span></i>
      </div>
    </div>
  </div>
</div>

app/views/layouts/client/base.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="thocodehoctiengnhat">
    <meta name="description" content="Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.">
    <meta name="keywords" content="luyện kanji, file luyện kanji, N5, N4, N3, N2, N1, Hiragana, Katakana, Hán tự, Học kanji"/>
    <meta property="og:locale" content="vi-VN" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Luyenkanji.com - Nền tảng chia sẻ phương pháp học kanji by tiktokID @thocodehoctiengnhat"/>
    <meta property="fb:app_id" content="" />
    <meta content='Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.' property='og:description'>
    <meta content='' property='og:image'>
    <meta content='vi_VN' property='og:locale'>
    <meta content='thocodehoctiengnhat' property='og:site_name'>
    <meta content='website' property='og:type'>
    <meta content='https://luyenkanji.com/' property='og:url'>
    <meta content='https://luyenkanji.com' property='og:see_also'>
    <title>Trang chủ | Luyenkanji.com - Ứng dụng luyện Kanji theo nét viết tay</title>
    <%= favicon_link_tag asset_path("favicon.svg"), rel: "icon", type: "image/x-icon" %>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body
    id="kt_app_body"
    data-kt-app-sidebar-enabled="true"
    data-kt-app-sidebar-fixed="true"
    data-kt-app-sidebar-push-header="true"
    data-kt-app-sidebar-push-toolbar="true"
    data-kt-app-sidebar-push-footer="true"
    class="app-default">
    <script>
      var defaultThemeMode = "light";
      var themeMode;
      if (document.documentElement) {
        if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
          themeMode =
            document.documentElement.getAttribute("data-bs-theme-mode");
        } else {
          if (localStorage.getItem("data-bs-theme") !== null) {
            themeMode = localStorage.getItem("data-bs-theme");
          } else {
            themeMode = defaultThemeMode;
          }
        }
        document.documentElement.setAttribute("data-bs-theme", themeMode);
      }
    </script>
    <div class="d-flex flex-column flex-root app-root" id="kt_app_root">
      <div class="app-page flex-column flex-column-fluid" id="kt_app_page">
        <%= render "shared/flash" %>
        <%= render "layouts/client/header" %>
        <div class="app-wrapper flex-column flex-row-fluid" id="kt_app_wrapper">
          <%= render "layouts/client/sidebar" %>
          <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
            <%= yield %>
            <%= render "layouts/client/footer" %>
          </div>
        </div>
      </div>
    </div>
    
    <%= render "layouts/client/modals/upgrade_plan" %>
    <%= render "layouts/client/modals/chat" %>

    <div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
      <i class="ki-outline ki-arrow-up"></i>
    </div>

    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/plugins.bundle.js"></script>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/scripts.bundle.js"></script>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/datatables.bundle.js"></script>
    <%= javascript_importmap_tags %>
  </body>
</html>