config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"

  mount Sidekiq::Web => "/sidekiq"

  root "client/dashboard#index"

  scope module: "client", path: "", as: "" do
    devise_for :accounts, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :records, only: [:new, :create, :show] do 
      member do
        get :hira_kata
        get :radical
        get :hira_kata_export_pdf
        get :radical_export_pdf
        get :kanji_export_pdf
      end
    end
    resources :accounts, only: [:show] do
      member do
        get :billing_history
      end
    end

    get "/search", to: "dashboard#search_kanji", as: :search_kanji
    get "/translate", to: "dashboard#translate", as: :translate
    get "/podcast", to: "dashboard#podcast", as: :podcast
    get "/checkout", to: "dashboard#checkout", as: :checkout
    get "/contact", to: "dashboard#contact", as: :contact
  end

  namespace :admin do
    root "dashboard#index"
   
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :accounts
    resources :histories, only: [:index, :show]
    resources :kanjis
    resources :story_kanjis
  end
end

app/models/history.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: histories
#
#  id           :bigint           not null, primary key
#  description  :text(65535)
#  title        :string(255)
#  type_history :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  account_id   :integer
#  plan_id      :integer
#  record_id    :integer
#
class History < ApplicationRecord
  belongs_to :account
  enum type_history: { download: "download", create_account: "create_account", upgrade_plan: "upgrade_plan",
       expire_plan: "expire_plan" }

  class << self
    def ransackable_attributes _auth_object = nil
      ["type_history"]
    end

    def ransackable_associations _auth_object = nil
      ["account"]
    end
  end
end

app/controllers/admin/histories_controller.rb
# frozen_string_literal: true

class Admin::HistoriesController < Admin::BaseController
  before_action :load_history, only: [:show]

  def index
    @q = History.ransack(params[:q])
    @pagy, @histories = pagy(@q.result.order(created_at: :desc))
  end

  def show
  end

  private

  def load_history
    @history = History.find(params[:id])
  end
end

app/views/admin/histories/_history.html.erb
<tr>
  <td>
    <a href="<%= admin_account_path(history.account) %>" class="text-gray-800 text-hover-primary mb-1" >
      <%= history.account.full_name %>
    </a>
  </td>
  <td>
    <a href="javascript:void(0)" class="text-gray-600 text-hover-primary mb-1"><%= history.account.email %></a>
  </td>
  <td>
    <div class="badge badge-light-danger"><%= history.account.role %></div>
  </td>
  <td><%= history.type_history %></td>
  <td><%= history.created_at.strftime("%H:%M, %d-%m-%Y") %></td>
  <td class="text-end">
    <a href="<%= admin_history_path(history) %>" class="btn btn-sm btn-light btn-flex btn-center btn-active-light-primary"> 
      <i class="ki-outline ki-eye fs-5">
        <span class="path1"></span>
        <span class="path2"></span>
        <span class="path3"></span>
      </i>
      chi tiết
    </a>
  </td>
</tr>

app/views/admin/histories/index.html.erb
<%= content_for :breadcum_first, "Trang chủ" %>
<%= content_for :breadcum_first_link, admin_root_path %>
<%= content_for :breadcum_second, "Hoạt động của người dùng" %>

<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-0">
  <div id="kt_app_toolbar_container" class="app-container container-xxl d-flex flex-stack">
    <div class="page-title d-flex flex-column justify-content-center me-3">
      <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">
        Hoạt động của toàn bộ người dùng
      </h1>
      <%= render "layouts/breadcrumb" %>
    </div>
  </div>
</div>
<div id="kt_app_content" class="app-content flex-column-fluid">
  <div id="kt_app_content_container" class="app-container container-xxl">
    <div class="card">
      <div class="card-header border-0 pt-6">
        <div class="card-title">
          <div class="d-flex align-items-center position-relative my-1">
            <i class="ki-outline ki-magnifier fs-3 position-absolute ms-5"></i>
            <%= search_form_for @q, url: admin_histories_path do |f| %>
              <%= f.search_field :account_full_name_or_account_role_or_account_email_or_type_history_cont, 
                class: "form-control form-control-solid w-250px ps-13", placeholder: "Tìm kiếm" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body pt-0">
        <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_customers_table">
          <thead>
            <tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
              <th class="min-w-125px">Người dùng</th>
              <th class="min-w-125px">Email</th>
              <th class="min-w-125px">Loại tài khoản</th>
              <th class="min-w-125px">Hành động</th>
              <th class="min-w-125px">Thời gian</th>
              <th class="text-end min-w-70px"></th>
            </tr>
          </thead>
          <tbody class="fw-semibold text-gray-600">
            <%= render @histories %>
          </tbody>
        </table>
        <div class="col-sm-12 col-md-12 d-flex align-items-center justify-content-md-end">
          <%= render partial: 'shared/pagination', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/histories/show.html.erb
show