config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"

  mount Sidekiq::Web => "/sidekiq"

  root "client/dashboard#index"

  scope module: "client", path: "", as: "" do
    devise_for :accounts, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :records, only: [:new, :create, :show] do 
      member do
        get :hira_kata
        get :radical
        get :hira_kata_export_pdf
        get :radical_export_pdf
        get :kanji_export_pdf
      end
    end
    resources :accounts, only: [:show] do
      member do
        get :billing_history
      end
    end

    get "/search", to: "dashboard#search_kanji", as: :search_kanji
    get "/translate", to: "dashboard#translate", as: :translate
    get "/podcast", to: "dashboard#podcast", as: :podcast
    get "/checkout", to: "dashboard#checkout", as: :checkout
    get "/contact", to: "dashboard#contact", as: :contact
  end

  namespace :admin do
    root "dashboard#index"
   
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :accounts
    resources :histories, only: [:index, :show]
    resources :kanjis
    resources :story_kanjis
  end
end

app/views/layouts/admin/_footer.html.erb
  <div id="kt_app_footer" class="app-footer">
    <div class="app-container container-xxl d-flex flex-column flex-md-row flex-center flex-md-stack py-3">
      <div class="text-dark order-2 order-md-1">
        <span class="text-muted fw-semibold me-1">2023&copy;</span>
        <a
          href="https://luyenkanji.com"
          target="_blank"
          class="text-gray-800 text-hover-primary"
          >luyenkanji.com, よ.</a
        >
      </div>
    </div>
  </div>

app/views/layouts/admin/_sidebar.html.erb
<div
  id="kt_app_sidebar"
  class="app-sidebar flex-column"
  data-kt-drawer="true"
  data-kt-drawer-name="app-sidebar"
  data-kt-drawer-activate="{default: true, lg: false}"
  data-kt-drawer-overlay="true"
  data-kt-drawer-width="275px"
  data-kt-drawer-direction="start"
  data-kt-drawer-toggle="#kt_app_sidebar_toggle">
  <div
    class="d-flex flex-stack px-4 px-lg-6 py-3 py-lg-8"
    id="kt_app_sidebar_logo">
    <a href="<%= admin_root_path %>">
      <img alt="Logo" src="<%= asset_path("media/logos/kanji-admin.svg")%>" class="h-20px h-lg-25px theme-light-show" />
      <img alt="Logo" src="<%= asset_path("media/logos/kanji-admin-dark.svg")%>" class="h-20px h-lg-25px theme-dark-show"/>
    </a>
    <% if admin_admin_signed_in? %>
      <div class="ms-3">
        <div class="cursor-pointer position-relative symbol symbol-circle symbol-40px"
          data-kt-menu-trigger="{default: 'click', lg: 'hover'}"
          data-kt-menu-attach="parent"
          data-kt-menu-placement="bottom-end">
          <img src="<%= asset_path("media/avatars/blank.png") %>" alt="user" />
          <div class="position-absolute rounded-circle bg-success start-100 top-100 h-8px w-8px ms-n3 mt-n3"></div>
        </div>
        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px"
          data-kt-menu="true">
          <div class="menu-item px-3">
            <div class="menu-content d-flex align-items-center px-3">
              <div class="symbol symbol-50px me-5">
                <img alt="Logo" src="<%= asset_path("media/avatars/blank.png") %>" />
              </div>
              <div class="d-flex flex-column">
                <div class="fw-bold d-flex align-items-center fs-5">
                  <%= current_admin_admin.full_name %>
                  <span class="badge badge-light-success fw-bold fs-8 px-2 py-1 ms-2">Pro</span>
                </div>
                <a href="#" class="fw-semibold text-muted text-hover-primary fs-7"><%= current_admin_admin.email %></a>
              </div>
            </div>
          </div>
          <div class="separator my-2"></div>
          <div class="menu-item px-5">
            <a href="<%#= admin_admin_path(current_admin_admin) %>" class="menu-link px-5">Hồ sơ cá nhân</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex-column-fluid px-4 px-lg-8 py-4" id="kt_app_sidebar_nav">
    <div id="kt_app_sidebar_nav_wrapper"
        class="d-flex flex-column hover-scroll-y pe-4 me-n4"
        data-kt-scroll="true"
        data-kt-scroll-activate="true"
        data-kt-scroll-height="auto"
        data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer"
        data-kt-scroll-wrappers="#kt_app_sidebar, #kt_app_sidebar_nav"
        data-kt-scroll-offset="5px">
      <div class="mb-6">
        <h3 class="text-gray-800 fw-bold mb-8">Quản lý</h3>
        <div
          class="row row-cols-3"
          data-kt-buttons="true"
          data-kt-buttons-target="[data-kt-button]"
        >
          <div class="col mb-4">
            <a
              href="<%= admin_kanjis_path %>"
              class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(admin_kanjis_path, "kanji", "index") %>"
              data-kt-button="true"
            >
              <span class="mb-2">
                <i class="ki-outline ki-calendar fs-1"></i>
              </span>
              <span class="fs-7 fw-bold">Kanji</span>
            </a>
          </div>
          <div class="col mb-4">
            <a
              href="<%= admin_story_kanjis_path %>"
              class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(admin_story_kanjis_path, "story_kanji", "index") %>"
              data-kt-button="true"
            >
              <span class="mb-2">
                <i class="ki-outline ki-devices fs-1"></i>
              </span>
              <span class="fs-7 fw-bold">Cách học</span>
            </a>
          </div>
          <div class="col mb-4">
            <a href="<%= admin_histories_path %>"
              class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(admin_histories_path, "history", "index") %>"
              data-kt-button="true">
              <span class="mb-2">
                <i class="ki-outline ki-security-check fs-1"></i>
              </span>
              <span class="fs-7 fw-bold">Hoạt động</span>
            </a>
          </div>
          <div class="col mb-4">
            <a href="<%= admin_accounts_path %>"
              class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(admin_accounts_path, "account", "index") %>"
              data-kt-button="true">
              <span class="mb-2">
                <i class="ki-outline ki-people fs-1"></i>
              </span>
              <span class="fs-7 fw-bold">Người dùng</span>
            </a>
          </div>
          <div class="col mb-4">
            <a href="<%= admin_root_path %>" class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(admin_root_path, "dashboard") %>"
              data-kt-button="true">
              <span class="mb-2">
                <i class="ki-outline ki-plus fs-1"></i>
              </span>
              <span class="fs-7 fw-bold">Mở rộng</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="aside-footer flex-column-auto px-4 px-lg-8 py-3 py-lg-8" id="kt_app_sidebar_footer">
    <div class="d-flex flex-stack">
      <% if admin_admin_signed_in? %>
        <div class="ms-7">
            <%= link_to destroy_admin_admin_session_path, class: "btn btn-sm btn-icon btn-active-color-primary btn-icon-gray-600 btn-text-gray-600" do %>
              <i class="ki-duotone ki-entrance-left fs-1 me-2"><span class="path1"></span><span class="path2"></span></i>
              <span class="d-flex flex-shrink-0 fw-bold">Đăng xuất</span>
            <% end %>
        </div>
      <% end %>
      <div class="btn btn-sm btn-icon btn-icon-gray-600 btn-active-color-primary position-relative me-n1">
        <i class="ki-duotone ki-setting-2 fs-1"><span class="path1"></span><span class="path2"></span></i>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="thocodehoctiengnhat">
    <meta name="description" content="Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.">
    <meta name="keywords" content="luyện kanji, file luyện kanji, N5, N4, N3, N2, N1, Hiragana, Katakana, Hán tự, Học kanji"/>
    <meta property="og:locale" content="vi-VN" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Luyenkanji.com - Nền tảng chia sẻ phương pháp học kanji by tiktokID @thocodehoctiengnhat"/>
    <meta property="fb:app_id" content="" />
    <meta content='Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.' property='og:description'>
    <meta content='' property='og:image'>
    <meta content='vi_VN' property='og:locale'>
    <meta content='thocodehoctiengnhat' property='og:site_name'>
    <meta content='website' property='og:type'>
    <meta content='https://luyenkanji.com/' property='og:url'>
    <meta content='https://luyenkanji.com' property='og:see_also'>
    <title>Admin | Luyenkanji.com - Ứng dụng luyện Kanji theo nét viết tay</title>
    <%= favicon_link_tag asset_path("favicon.svg"), rel: "icon", type: "image/x-icon" %>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body
    id="kt_app_body"
    data-kt-app-sidebar-enabled="true"
    data-kt-app-sidebar-fixed="true"
    data-kt-app-sidebar-push-header="true"
    data-kt-app-sidebar-push-toolbar="true"
    data-kt-app-sidebar-push-footer="true"
    class="app-default">
    <script>
      var defaultThemeMode = "light";
      var themeMode;
      if (document.documentElement) {
        if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
          themeMode =
            document.documentElement.getAttribute("data-bs-theme-mode");
        } else {
          if (localStorage.getItem("data-bs-theme") !== null) {
            themeMode = localStorage.getItem("data-bs-theme");
          } else {
            themeMode = defaultThemeMode;
          }
        }
        if (themeMode === "system") {
          themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        }
        document.documentElement.setAttribute("data-bs-theme", themeMode);
      }
    </script>
    <div class="d-flex flex-column flex-root app-root" id="kt_app_root">
      <div class="app-page flex-column flex-column-fluid" id="kt_app_page">
        <%= render "shared/flash" %>
        <%= render "layouts/admin/header" %>
        <div class="app-wrapper flex-column flex-row-fluid" id="kt_app_wrapper">
          <%= render "layouts/admin/sidebar" %>
          <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
            <div class="d-flex flex-column flex-column-fluid">
              <%= yield %>
            </div>
            <%= render "layouts/admin/footer" %>
          </div>
        </div>
      </div>
    </div>
    
    <div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
      <i class="ki-outline ki-arrow-up"></i>
    </div>

    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/plugins.bundle.js"></script>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/scripts.bundle.js"></script>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/datatables.bundle.js"></script>

    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/layouts/admin/unauthenticate_layout.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="thocodehoctiengnhat">
    <meta name="description" content="Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.">
    <meta name="keywords" content="luyện kanji, file luyện kanji, N5, N4, N3, N2, N1, Hiragana, Katakana, Hán tự, Học kanji"/>
    <meta property="og:locale" content="vi-VN" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Luyenkanji.com - Nền tảng chia sẻ phương pháp học kanji by tiktokID @thocodehoctiengnhat"/>
    <meta property="fb:app_id" content="" />
    <meta content='Website chia sẻ tài liệu luyện viết Kanji - nguồn tài liệu học tập tốt nhất dành cho những ai đang bắt đầu khám phá thế giới phức tạp của Kanji. Tại đây, chúng tôi cung cấp một công cụ tạo chữ hán chất lượng cao. Hãy bắt đầu cùng chúng tôi để tìm hiểu, thực hành và nắm vững các cấu tạo của mọi Kanji.' property='og:description'>
    <meta content='' property='og:image'>
    <meta content='vi_VN' property='og:locale'>
    <meta content='thocodehoctiengnhat' property='og:site_name'>
    <meta content='website' property='og:type'>
    <meta content='https://luyenkanji.com/' property='og:url'>
    <meta content='https://luyenkanji.com' property='og:see_also'>
    <title>Đăng Nhập | Luyenkanji.com - Ứng dụng luyện Kanji theo nét viết tay</title>
    <%= favicon_link_tag asset_path("favicon.svg"), rel: "icon", type: "image/x-icon" %>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google" content="notranslate">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700"/>
    <style>
      body {
        background-image: url('<%= asset_path("bg10.jpg") %>');
      }
    </style>
  </head>
  <body id="kt_body"
    class="app-blank bgi-size-cover bgi-attachment-fixed bgi-position-center">
    <script>
      var defaultThemeMode = "light";
      var themeMode;
      if (document.documentElement) {
        if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
          themeMode =
            document.documentElement.getAttribute("data-bs-theme-mode");
        } else {
          if (localStorage.getItem("data-bs-theme") !== null) {
            themeMode = localStorage.getItem("data-bs-theme");
          } else {
            themeMode = defaultThemeMode;
          }
        }
        if (themeMode === "system") {
          themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        }
        document.documentElement.setAttribute("data-bs-theme", themeMode);
      }
    </script>
    <%= render "shared/flash" %>
    <div class="d-flex flex-column flex-root" id="kt_app_root">
      <div class="d-flex flex-column flex-lg-row flex-column-fluid">
        <div class="d-flex flex-lg-row-fluid">
          <div class="d-flex flex-column flex-center pb-0 pb-lg-10 p-10 w-100"> 
            <img class="theme-light-show mx-auto mw-100 w-150px w-lg-300px mb-10 mb-lg-20" src="<%= asset_path('agency.png') %>" alt=""/>    
            <h1 class="text-gray-800 fs-2x fw-bold text-center mb-7"> 
              Khám phá thế giới Kanji qua phương pháp luyện nét
            </h1>  
            <div class="text-gray-600 fs-base text-center fw-semibold">
              Ở website này, <a href="#" class="opacity-75-hover text-primary">Chúng tôi</a> 
              đã phát triển 1 ứng dụng <br/> tạo chữ hán theo nét viết tay
              <br/> hi vọng mang lại sự hiệu quả nhất định trong quá trình học tiếng Nhật cho các bạn.  
            </div>
          </div>
        </div>
        <div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
          <div class="bg-body d-flex flex-column flex-center rounded-4 w-md-600px p-10">
            <div class="d-flex flex-center flex-column align-items-stretch h-lg-100 w-md-400px">
              <div class="d-flex flex-center flex-column-fluid pb-15 pb-lg-20">
                <div class="form w-100">
                  <div class="text-center mb-11">
                    <h1 class="text-dark fw-bolder mb-3">
                      Đăng Nhập
                    </h1>
                  </div>
                  <div class="separator separator-content my-14">
                    <span class="w-100px text-gray-500 fw-semibold fs-7">Với email</span>
                  </div>
                  <%= yield %>
                </div>
              </div>
              <div class=" d-flex flex-stack">
                <div class="me-10">             
                  <button class="btn btn-flex btn-link btn-color-gray-700 btn-active-color-primary rotate fs-base" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-start" data-kt-menu-offset="0px, 0px">
                    <img  data-kt-element="current-lang-flag" class="w-20px h-20px rounded me-3" src="<%= asset_path('flags/vietnam.svg')%>" alt=""/>
                    <span data-kt-element="current-lang-name" class="me-1">Tiếng Việt</span>
                    <span class="svg-icon svg-icon-5 svg-icon-muted rotate-180 m-0">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor"/>
                      </svg>
                    </span>
                  </button>
                  <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-4 fs-7" data-kt-menu="true" id="kt_auth_lang_menu">
                    <div class="menu-item px-3">
                      <a href="#" class="menu-link d-flex px-5" data-kt-lang="Vietnam">
                        <span class="symbol symbol-20px me-4">
                          <img data-kt-element="lang-flag" class="rounded-1" src="<%= asset_path('flags/vietnam.svg')%>" alt=""/>
                        </span>
                        <span data-kt-element="lang-name">Tiếng Việt</span>
                      </a>
                    </div>
                    <div class="menu-item px-3">
                      <a href="#" class="menu-link d-flex px-5" data-kt-lang="Japanese">
                        <span class="symbol symbol-20px me-4">
                          <img data-kt-element="lang-flag" class="rounded-1" src="<%= asset_path('flags/japan.svg')%>" alt=""/>
                        </span>
                        <span data-kt-element="lang-name">日本語</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="d-flex fw-semibold text-primary fs-base gap-5">
                  <a href="" target="_blank">Chính sách bảo mật</a>
                  <a href="" target="_blank">Liên hệ chúng tôi</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/plugins.bundle.js"></script>
    <script src="https://haotv.s3.ap-southeast-1.amazonaws.com/scripts.bundle.js"></script>
    <%= javascript_importmap_tags %>
  </body>
</html>