config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"

  mount Sidekiq::Web => "/sidekiq"

  root "client/dashboard#index"

  scope module: "client", path: "", as: "" do
    devise_for :accounts, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :records, only: [:new, :create, :show] do 
      member do
        get :hira_kata
        get :radical
        get :hira_kata_export_pdf
        get :radical_export_pdf
        get :kanji_export_pdf
      end
    end
    resources :accounts, only: [:show] do
      member do
        get :billing_history
      end
    end

    get "/search", to: "dashboard#search_kanji", as: :search_kanji
    get "/translate", to: "dashboard#translate", as: :translate
    get "/podcast", to: "dashboard#podcast", as: :podcast
    get "/checkout", to: "dashboard#checkout", as: :checkout
    get "/contact", to: "dashboard#contact", as: :contact
  end

  namespace :admin do
    root "dashboard#index"
   
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }

    resources :accounts
    resources :histories, only: [:index, :show]
    resources :kanjis
    resources :story_kanjis
  end
end

app/controllers/client/accounts_controller.rb
# frozen_string_literal: true

class Client::AccountsController < Client::BaseController
  before_action :set_account, only: [:show, :billing_history]

  def show
  end

  def billing_history
  end

  private

  def set_account
    @account = Account.friendly.find(params[:id])
  end
end

app/controllers/client/base_controller.rb
# frozen_string_literal: true

class Client::BaseController < ApplicationController
  # before_action :authenticate_account!
end

app/controllers/client/dashboard_controller.rb
# frozen_string_literal: true

class Client::DashboardController < Client::BaseController
  def index
    @record = Record.new
  end

  def search_kanji
    @q = Kanji.ransack(params[:q])
    @pagy, @kanjis = pagy(@q.result.order(created_at: :desc))

    @kanji = (@kanjis.last if @kanjis.count == 1)
  end

  def translate
  end

  def podcast
  end

  def checkout
  end

  def contact
  end
end

app/controllers/client/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Client::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    generic_callback(:google_oauth2)
  end

  def generic_callback provider
    @account = Account.from_omniauth(request.env["omniauth.auth"])
    account_exits = Account.where("email = ? and provider != ?", @account.email, provider).take
    return handle_account_exits(account_exits, provider) if account_exits

    if @account.persisted?
      set_flash_message(:notice, :success, kind: provider.capitalize)
    else
      @account.email = @account.uid if @account.email.blank?
      @account.save(validate: false)
      @account.histories.create(
        type_history: "create_account",
        title: "Chào mừng bạn đến với hệ thống!",
        description: "Chúc bạn có những trải nghiệm thú vị trong hành trình học tiếng Nhật."
      )
      ActionAccountMailer.send_email_welcome(@account.email, @account.full_name).deliver_later
    end
    @account.update last_sign_in_at: Time.zone.now
    sign_in_and_redirect @account, event: :authentication
  end

  def failure
    redirect_to root_path
  end

  private

  def handle_account_exits account_exits, provider
    account_exits.uid = @account.uid
    account_exits.provider = provider

    account_exits.save
    set_flash_message(:notice, :success, kind: provider.capitalize)
    sign_in_and_redirect account_exits, event: :authentication
  end
end

app/controllers/client/records_controller.rb
# frozen_string_literal: true

class Client::RecordsController < Client::BaseController
  before_action :render_service,
    only: [:show, :hira_kata, :radical, :hira_kata_export_pdf, :radical_export_pdf, :kanji_export_pdf]
  before_action :set_record, only: :show

  def show # rubocop:disable Metrics/PerceivedComplexity
    if @record.hiragana? || @record.katakana?
      if @record.kanji_list.include?("じ") || @record.kanji_list.include?("ジ")
        redirect_to hira_kata_record_path(@record)
      else
        flash[:error] = "Tạo bản nháp Hiragana hoặc Katakana nhưng nội dung không khớp, vui lòng chọn lại"
        redirect_to root_path
      end
    end

    return unless @record.sub_kanji?

    if @record.kanji_list.include?("衣")
      redirect_to radical_record_path(@record)
    else
      flash[:error] = "Tạo bản nháp 214 bộ thủ nhưng nội dung không khớp, vui lòng chọn lại"
      redirect_to root_path
    end
  end

  def create # rubocop:disable Metrics/MethodLength,Metrics/PerceivedComplexity
    unless account_signed_in?
      flash[:error] = "Bạn cần đăng nhập để sử dụng tính năng này"
      redirect_to root_path
      return
    end

    if current_account.advanced?
      @record = Record.new record_params
      @record.account_id = current_account.id
      @record.name = "Code=#{SecureRandom.uuid}-#{Time.zone.now.to_i}"

      if @record.save
        flash[:success] = "Tạo bản ghi thành công."
        current_account.histories.create(
          type_history: "download",
          title: "Tạo bản nháp thành công.",
          description: "Chúc bạn học thật tốt với file luyện viết này",
          record_id: @record.id
        )
        redirect_to @record
      else
        flash[:error] = "Tạo bản ghi thất bại."
        redirect_to root_path
      end
    elsif record_params[:type_record] == "hiragana" ||
          record_params[:type_record] == "katakana" || record_params[:type_record] == "sub_kanji"
      @record = Record.new record_params
      @record.account_id = current_account.id
      @record.name = "Code=#{SecureRandom.uuid}-#{Time.zone.now.to_i}"
      @record.title = "luyenkanji.com | @thocodehoctiengnhat"

      if @record.save
        flash[:success] = "Tạo bản ghi thành công."
        current_account.histories.create(
          type_history: "download",
          title: "Tạo bản nháp thành công.",
          description: "Chúc bạn học thật tốt với file luyện viết này",
          record_id: @record.id
        )
        redirect_to @record
      else
        flash[:error] = "Tạo bản ghi thất bại."
        redirect_to root_path
      end
    else
      flash[:error] = "Bạn cần nâng cấp tài khoản để sử dụng tùy chọn này."
      redirect_to root_path
    end
  end

  def hira_kata
  end

  def radical
  end

  def hira_kata_export_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
          template: "client/records/hira_kata_export_pdf",
          formats: [:html],
          disposition: :attachment,
          layout: "pdf"
      end
    end
  end

  def radical_export_pdf
    render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
      disposition: "attachment",
      layout: "pdf"
  end

  def kanji_export_pdf
    render pdf: "[Luyenkanji.com]_#{Time.zone.now.strftime('%Y%m%d%H%M')}_#{@record.type_record}",
      disposition: "attachment",
      layout: "pdf"
  end

  private

  def record_params
    params.require(:record).permit Record::ATTRS
  end

  def set_record
    @record = Record.friendly.find(params[:id])
  end

  def render_service
    @record = Record.friendly.find(params[:id])
    svg = HandleSvgService.new
    @list_path = svg.handle_kanji @record.kanji_list
  end
end

app/controllers/client/sessions_controller.rb
# frozen_string_literal: true

class Client::SessionsController < Devise::SessionsController
  layout "client/unauthenticate_layout"

  def destroy
    flash[:success] = I18n.t("devise.sessions.signed_out") if sign_out current_account
    redirect_to new_account_session_path
  end
end

app/views/layouts/client/modals/_chat.html.erb
<div
  id="kt_drawer_chat"
  class="bg-body"
  data-kt-drawer="true"
  data-kt-drawer-name="chat"
  data-kt-drawer-activate="true"
  data-kt-drawer-overlay="true"
  data-kt-drawer-width="{default:'300px', 'md': '500px'}"
  data-kt-drawer-direction="end"
  data-kt-drawer-toggle="#kt_drawer_chat_toggle"
  data-kt-drawer-close="#kt_drawer_chat_close">
  <div class="card w-100 border-0 rounded-0" id="kt_drawer_chat_messenger">
    <div class="card-header pe-5" id="kt_drawer_chat_messenger_header">
      <div class="card-title">
        <div class="d-flex justify-content-center flex-column me-3">
          <a
            href="#"
            class="fs-4 fw-bold text-gray-900 text-hover-primary me-1 mb-2 lh-1"
            >Quản trị viên</a
          >
          <div class="mb-0 lh-1">
            <span
              class="badge badge-success badge-circle w-10px h-10px me-1"
            ></span>
            <span class="fs-7 fw-semibold text-muted">Active</span>
          </div>
        </div>
      </div>
      <div class="card-toolbar">
        <div
          class="btn btn-sm btn-icon btn-active-color-primary"
          id="kt_drawer_chat_close"
        >
          <i class="ki-outline ki-cross-square fs-2"></i>
        </div>
      </div>
    </div>
    <div class="card-body" id="kt_drawer_chat_messenger_body">
      <div
        class="scroll-y me-n5 pe-5"
        data-kt-element="messages"
        data-kt-scroll="true"
        data-kt-scroll-activate="true"
        data-kt-scroll-height="auto"
        data-kt-scroll-dependencies="#kt_drawer_chat_messenger_header, #kt_drawer_chat_messenger_footer"
        data-kt-scroll-wrappers="#kt_drawer_chat_messenger_body"
        data-kt-scroll-offset="0px"
      >
        <div class="d-flex justify-content-start mb-10">
          <div class="d-flex flex-column align-items-start">
            <div class="d-flex align-items-center mb-2">
              <div class="symbol symbol-35px symbol-circle">
                <img alt="Pic" src="<%= asset_path("media/avatars/blank.png") %>" />
              </div>
              <div class="ms-3">
                <a
                  href="#"
                  class="fs-5 fw-bold text-gray-900 text-hover-primary me-1"
                  >Quản trị viên</a
                >
                <span class="text-muted fs-7 mb-1">2 mins</span>
              </div>
            </div>
            <div
              class="p-5 rounded bg-light-info text-dark fw-semibold mw-lg-400px text-start"
              data-kt-element="message-text"
            >
              Chức năng đang được hoàn thiện.
            </div>
          </div>
        </div>
        
      </div>
    </div>
    <div class="card-footer pt-4" id="kt_drawer_chat_messenger_footer">
      <textarea
        class="form-control form-control-flush mb-3"
        rows="1"
        data-kt-element="input"
        placeholder="Nhập nội dung"
      ></textarea>
      <div class="d-flex flex-stack">
        <div class="d-flex align-items-center me-2">
          <button
            class="btn btn-sm btn-icon btn-active-light-primary me-1"
            type="button"
            data-bs-toggle="tooltip"
            title="chức năng đang hoàn thiện"
          >
            <i class="ki-outline ki-paper-clip fs-3"></i>
          </button>
          <button
            class="btn btn-sm btn-icon btn-active-light-primary me-1"
            type="button"
            data-bs-toggle="tooltip"
            title="chức năng đang hoàn thiện"
          >
            <i class="ki-outline ki-cloud-add fs-3"></i>
          </button>
        </div>
        <button
          class="btn btn-primary"
          type="button"
          data-kt-element="send"
        >
          Gửi
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/client/modals/_service.html.erb
<div class="mb-6">
  <h3 class="text-gray-800 fw-bold mb-8">Tiện ích</h3>
  <div
    class="row row-cols-3"
    data-kt-buttons="true"
    data-kt-buttons-target="[data-kt-button]"
  >
    <div class="col mb-4">
      <a
        href="<%= search_kanji_path %>"
        class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(search_kanji_path, "dashboard", "search_kanji") %>"
        data-kt-button="true"
      >
        <span class="mb-2">
          <i class="ki-outline ki-calendar fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Tìm Kanji</span>
      </a>
    </div>
    <div class="col mb-4">
      <a href="<%= translate_path %>"
        class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(translate_path, "dashboard", "translate") %>"
        data-kt-button="true">
        <span class="mb-2">
          <i class="ki-outline ki-security-check fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Dịch bằng AI</span>
      </a>
    </div>
    <div class="col mb-4">
      <a href="<%= podcast_path %>"
        class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px  <%= active_sidebar(podcast_path, "dashboard", "podcast") %>"
        data-kt-button="true">
        <span class="mb-2">
          <i class="ki-outline ki-wifi-square fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Nghe hiểu</span>
      </a>
    </div>
    <div class="col mb-4">
      <a
        href=""
        class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px border-gray-200"
        data-kt-button="true"
      >
        <span class="mb-2">
          <i class="ki-outline ki-chart-line-up-2 fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Đọc hiểu</span>
      </a>
    </div>
    <div class="col mb-4">
      <a href="" class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px border-gray-200"
        data-kt-button="true">
        <span class="mb-2">
          <i class="ki-outline ki-shield-tick fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Thảo luận</span>
      </a>
    </div>
    <div class="col mb-4">
      <a href="<%= root_path %>" class="btn btn-icon btn-outline btn-bg-light btn-active-light-primary btn-flex flex-column flex-center w-lg-90px h-lg-90px w-70px h-70px <%= active_sidebar(root_path, "dashboard") %>"
        data-kt-button="true">
        <span class="mb-2">
          <i class="ki-outline ki-geolocation-home fs-1"></i>
        </span>
        <span class="fs-7 fw-bold">Trang chủ</span>
      </a>
    </div>
  </div>
</div>

app/views/layouts/client/modals/_upgrade_plan.html.erb
<div
  class="modal fade"
  id="kt_modal_upgrade_plan"
  tabindex="-1"
  aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content rounded">
      <div class="modal-header justify-content-end border-0 pb-0">
        <div
          class="btn btn-sm btn-icon btn-active-color-primary"
          data-bs-dismiss="modal"
        >
          <i class="ki-outline ki-cross fs-1"></i>
        </div>
      </div>
      <div class="modal-body pt-0 pb-15 px-5 px-xl-20">
        <div class="mb-13 text-center">
          <h1 class="mb-3">Nâng cấp tài khoản</h1>
          <div class="text-muted fw-semibold fs-5">
            Nếu có thắc mắc và muốn giải đáp
            <a href="#" class="link-primary fw-bold">vui lòng liên hệ tôi</a>.
          </div>
        </div>
        <div class="d-flex flex-column">
          <div class="row mt-10">
            <div class="col-lg-6 mb-10 mb-lg-0">
              <div class="nav flex-column">
                <label
                  class="nav-link btn btn-outline btn-outline-dashed btn-color-dark btn-active btn-active-primary d-flex flex-stack text-start p-6 active mb-6"
                  data-bs-toggle="tab"
                  data-bs-target="#kt_upgrade_plan_startup"
                >
                  <div class="d-flex align-items-center me-2">
                    <div
                      class="form-check form-check-custom form-check-solid form-check-success flex-shrink-0 me-6"
                    >
                      <input
                        class="form-check-input"
                        type="radio"
                        name="plan"
                        checked="checked"
                        value="startup"
                      />
                    </div>
                    <div class="flex-grow-1">
                      <div
                        class="d-flex align-items-center fs-2 fw-bold flex-wrap"
                      >
                        Miễn phí
                      </div>
                      <div class="fw-semibold opacity-75">
                        Bản mềm luyện viết Hiragana, Katakana, Bộ thủ
                      </div>
                    </div>
                  </div>
                  <div class="ms-5">
                    <span
                      class="fs-2x fw-bold"
                      data-kt-plan-price-month="0"
                      >0</span
                    >
                    <span class="mb-2">vnđ</span>
                  </div>
                </label>
                <label
                  class="nav-link btn btn-outline btn-outline-dashed btn-color-dark btn-active btn-active-primary d-flex flex-stack text-start p-6 mb-6"
                  data-bs-toggle="tab"
                  data-bs-target="#kt_upgrade_plan_enterprise"
                >
                  <div class="d-flex align-items-center me-2">
                    <div
                      class="form-check form-check-custom form-check-solid form-check-success flex-shrink-0 me-6"
                    >
                      <input
                        class="form-check-input"
                        type="radio"
                        name="plan"
                        value="enterprise"
                      />
                    </div>
                    <div class="flex-grow-1">
                      <div
                        class="d-flex align-items-center fs-2 fw-bold flex-wrap"
                      >
                        Nâng Cao
                        <span
                          class="badge badge-light-success ms-2 py-2 px-3 fs-7"
                          >Khuyên dùng</span
                        >
                      </div>
                      <div class="fw-semibold opacity-75">
                        Sử dụng tất cả các tiện ích vĩnh viễn
                      </div>
                    </div>
                  </div>
                  <div class="ms-5">
                    <span
                      class="fs-2x fw-bold"
                      data-kt-plan-price-month="199.000"
                      >199.000</span
                    >
                    <span class="mb-2">vnđ</span>
                  </div>
                </label>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="tab-content rounded h-100 bg-light p-10">
                <div class="tab-pane fade show active" id="kt_upgrade_plan_startup">
                  <div class="pb-5">
                    <h2 class="fw-bold text-dark">
                      Miễn phí có những gì?
                    </h2>
                    <div class="text-muted fw-semibold">
                      Bản mềm luyện viết hiragana, katakana, 214 bộ thủ
                    </div>
                  </div>
                  <div class="pt-1">
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm Hiragana</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm Katakana</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm 214 Bộ thủ</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Cấu tạo từng nét Kanji</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>

                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-muted flex-grow-1"
                        >Tùy chọn kanji đang yếu</span
                      >
                      <i class="ki-outline ki-cross-circle fs-1"></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-muted flex-grow-1"
                        >Bản mềm Kanji N5, 4, 3, 2, 1</span
                      >
                      <i class="ki-outline ki-cross-circle fs-1"></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-muted flex-grow-1"
                        >Bỏ hiển thị bản quyền trên bản mềm</span
                      >
                      <i class="ki-outline ki-cross-circle fs-1"></i>
                    </div>
                    <div class="d-flex align-items-center">
                      <span class="fw-semibold fs-5 text-muted flex-grow-1"
                        >Sử dụng dịch của Chat-GPT 4.0</span
                      >
                      <i class="ki-outline ki-cross-circle fs-1"></i>
                    </div>
                  </div>
                </div>
                <div class="tab-pane fade" id="kt_upgrade_plan_enterprise">
                  <div class="pb-5">
                    <h2 class="fw-bold text-dark">
                      Gói nâng cao có những gì?
                    </h2>
                    <div class="text-muted fw-semibold">
                      Tùy chọn hơn 2500 hán tự, dịch Việt-Nhật, Nhật-Việt bằng Chat-GPT 4.0 
                    </div>
                  </div>
                  <div class="pt-1">
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm Hiragana</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm Katakana</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span
                        class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm 214 Bộ thủ</span
                      >
                      <i
                        class="ki-outline ki-check-circle fs-1 text-success"
                      ></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Cấu tạo từng nét Kanji</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>

                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Tùy chọn kanji đang yếu</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bản mềm Kanji N5, 4, 3, 2, 1</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Bỏ hiển thị bản quyền trên bản mềm</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>
                    <div class="d-flex align-items-center mb-7">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Tùy chỉnh hiển thị bản quyền trên bản mềm</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>
                    <div class="d-flex align-items-center">
                      <span class="fw-semibold fs-5 text-gray-700 flex-grow-1"
                        >Sử dụng dịch bằng Chat-GPT 4.0</span
                      >
                      <i class="ki-outline ki-check-circle fs-1 text-success"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="d-flex flex-center flex-row-fluid pt-12">
          <button
            type="reset"
            class="btn btn-light me-3"
            data-bs-dismiss="modal"
          >
            Hủy bỏ
          </button>
          <a
            href="<%= checkout_path %>"
            class="btn btn-primary"
            id="kt_modal_upgrade_plan_btn"
          >
            <span class="indicator-label">Nâng cấp ngay</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>